name: release

on:
  push:
    tags:
      - "v*"

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-26.05

      - uses: cachix/cachix-action@v17
        with:
          name: skyethepinkcat
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build nvim-config-export
        run: nix build .#nixvim-config-export-archive --impure --no-link --print-out-paths > store_path.txt

      - name: Package as tar.gz
        run: |
          STORE_PATH=$(cat store_path.txt)
          cp $STORE_PATH/nvim.tar.gz nvim.tar.gz

      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: nvim.tar.gz
